build:
  stage: build
  only:
  - tags
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
  # - docker run --rm ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} /bin/bash -c 'npm test'
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
